// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Recital struct {
	ID          int32
	Url         string
	Title       string
	Description string
	Status      string
	Path        string
	CreatedAt   pgtype.Date
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Date
}
