version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: recite-db
    ports:
      - "5427:5432"
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recite"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
